apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: app
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - image: busybox:1.34
        name: init-mysql-check
        envFrom:
          - configMapRef:
              name: wordpress-env
        command:
        - sh
        - -c
        - |
          until nc -z $WORDPRESS_DB_HOST 3306;
          do
            echo -e "[-] Waiting for MySQL response...";
            sleep 3;
          done;
          echo -e "[+] MySQL is up and running!";
      containers:
      - image: wordpress
        name: wordpress
        envFrom:
          - configMapRef:
              name: wordpress-env
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-env
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-mysql-env
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-pvc